name: myanmar_kit_example
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.12.2
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^8.1.0
  myanmar_kit:
    path: ..

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
